### ISSUE TITLE
Reduce downtime during updates

### ISSUE THREAD

**Issue by mtdcr** [jaypikay/doxy#2]
The current workflow is `stop`/`down` -> `pull` -> `up`.

I haven't figured out the optimal way, but it seems like a single `docker compose up -d --pull always` would be sufficient to rebuild and restart. Unfortunately, the container gets restarted even if there were no changes to images or configuration.

**Comment by jaypikay** [comment]
Thanks. I could use this instead of the `stop` command. The `down` is used to remove unused volumes.

**Comment by jaypikay** [comment]
I have implemented a variant of this in 0.5.1
